name: AsciiDoc-Publisher

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: AsciiDoc HTML generator and publisher
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get build container
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D doc --backend=html5 -o html/index.html doc/lightoros.adoc"

      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./html